name: Tron Wallet Monitor

on:
  schedule:
    - cron: "*/10 * * * *" # ogni 10 minuti
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor script
        run: python main.py
